require('core.plugin_config.vimtex')
require('core.plugin_config.fzf-lua')
require('core.plugin_config.lualine')
require('core.plugin_config.nvim-tree')
require("core.plugin_config.treesitter") 
require('core.plugin_config.toggleterm')
