require('core.plugin_config.oil')
require('core.plugin_config.telescope')
require('core.plugin_config.snippy')
require('core.plugin_config.lsp_config')
require('core.plugin_config.vimtex')
require('core.plugin_config.lualine')
require("core.plugin_config.treesitter")
require('core.plugin_config.toggleterm')
