# Put in ~/.config
format = """
$status \
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

add_newline=true
command_timeout=3000 #ms

[aws]
disabled = true

[character]
format = "❯❯ "
success_symbol = "❯❯(bold green) "
error_symbol = "❯❯(bold red) "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[git_status]
modified = "➜"

[hostname] 
ssh_only = false 
format = 'on [$hostname](bold purple) ' 
trim_at = "." 
disabled = false


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = false
time_format = "%Y-%m-%d %H:%M"
utc_time_offset = "local"

[username]
style_root = "green bold"
format = "ϕ [$user]($style) "
disabled = false
show_always = true

[git_branch]
symbol = "β "
truncation_length = 50
truncation_symbol = "…"
style="bold purple"

